dvision:
    points_a:
        [
            25, 25, # 0
            25, -25,
            50, 50,
            50, -50,
            75, 0,
            0, 75,
            0, -75,
            75, 75,
            75, -75,
            100, 0,
            150, 0, # 10: not used
            0, -150,
            0, 150, # 12: miss
            0, 150,
            100, 50,
            100, -50,
            25, 75,
            25, -75,
            50, 75,
            50, -75,
            25, 50, # 20
            25, -50,
            50, 25,
            50, -25,
            50, 0,
            25, 0,
            75, 50,
            75, -50,
            75, 25,
            75, -25,
            100, -145, # 30
            65, -145,
            30, -145,
            100, -110,
            65, -110,
            30, -110,
            100, 110,
            65, 110,
            30, 110
        ]
    points_b:
        [
            125, -35, # 0
            175, -35,
            100, -10,
            200, -10,
            150, 15,
            75, -60,
            225, -60,
            75, 15,
            225, 15,
            150, 40,
            150, 90, # 10
            300, -60,
            0, -60,
            0, -60,
            100, 40,
            200, 40,
            75, -35,
            225, -35,
            75, -10,
            225, -10,
            100, -35, # 20
            200, -35,
            125, -10,
            175, -10,
            150, -10,
            150, -35,
            100, 15,
            200, 15,
            125, 15,
            175, 15,
            295, 40, # 30
            295, 5,
            295, -30,
            260, 40,
            260, 5,
            260, -30,
            40, 40,
            40, 5,
            40, -30, # 38
            0, 0, # 39, empty
            400, -48, # 40
            400, -16,
            400, 16,
            400, 48
        ]
